config/routes.rb
Skillexchange::Application.routes.draw do
  resources :offers

  root :to => "static_pages#home"

  resources :keywords
  resources :skills
  resources :courses
  resources :users
  resources :offers

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :offers do 
     collection do
      get 'search'
     end
  end

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  attr_accessible :place, :skill_id, :time, :user_id

  def search
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition, search_condition])
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  @keywords= Keyword.find(:all, :conditions => ['keyword LIKE ?', "%#{search}%"])
  @offers = Offer.all
  # @skills = .find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  # @offers = Offer.find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
   
   #@offers = Offer.search params[:search]
  #  @offer = Offer.find(params[:id])

   # respond_to do |format|
    #  format.html # show.html.erb
   #   format.json { render json: @offer }
   # end
  end

  # GET /offers/new
  # GET /offers/new.json
  def new
    @offer = Offer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(params[:offer])

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render json: @offer, status: :created, location: @offer }
      else
        format.html { render action: "new" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end

  def search
   #@offers = Offer.find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    #@offers = Offer.search params[:search]

  end 

end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skill_id %><br />
    <%= f.number_field :skill_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/_search.html.erb
 <%= form_tag :controller => 'offers', :action => 'search', :method => 'get' do %>
   <%= text_field_tag :search, params[:search], :id => 'search_field' %>
   <%= submit_tag "Search for something special to learn", :name => nil %> 
<% end %>
<form action="/offers/search" method="get" class="search_field">
   <input type="text" placeholder="Search" class="search-query span2" name="query">
</form>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

<table>
  <tr>
    <th>Skill</th>
    <th>User</th>
    <th>Place</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offers.each do |offer| %>
  <tr>
    <td><%= offer.skill_id %></td>
    <td><%= offer.user_id %></td>
    <td><%= offer.place %></td>
    <td><%= offer.time %></td>
    <td><%= link_to 'Show', offer %></td>
    <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
    <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<h1>Listing offers</h1>

<table>
  <tr>
    <th>Skill</th>
    <th>User</th>
    <th>Place</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offers.each do |offer| %>
  <tr>
    <td><%= offer.skill_id %></td>
    <td><%= offer.user_id %></td>
    <td><%= offer.place %></td>
    <td><%= offer.time %></td>
    <td><%= link_to 'Show', offer %></td>
    <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
    <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Offer', new_offer_path %>