config/routes.rb
Skillexchange::Application.routes.draw do
  resources :offers

  root :to => "static_pages#home"

  resources :keywords
  resources :skills
  resources :courses
  resources :users
  resources :offers

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :offers do 
     collection do
      get 'search'
     end
  end

end

app/models/keyword.rb
# == Schema Information
#
# Table name: keywords
#
#  id         :integer          not null, primary key
#  skillId    :integer
#  keyword    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Keyword < ActiveRecord::Base
  attr_accessible :keyword, :skillId
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @keywords }
    end
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
    @keyword = Keyword.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @keyword }
    end
  end

  # GET /keywords/new
  # GET /keywords/new.json
  def new
    @keyword = Keyword.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @keyword }
    end
  end

  # GET /keywords/1/edit
  def edit
    @keyword = Keyword.find(params[:id])
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(params[:keyword])

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render json: @keyword, status: :created, location: @keyword }
      else
        format.html { render action: "new" }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /keywords/1
  # PUT /keywords/1.json
  def update
    @keyword = Keyword.find(params[:id])

    respond_to do |format|
      if @keyword.update_attributes(params[:keyword])
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword = Keyword.find(params[:id])
    @keyword.destroy

    respond_to do |format|
      format.html { redirect_to keywords_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skillId %><br />
    <%= f.number_field :skillId %>
  </div>
  <div class="field">
    <%= f.label :keyword %><br />
    <%= f.text_field :keyword %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<h1>Listing keywords</h1>

<table>
  <tr>
    <th>Skillid</th>
    <th>Keyword</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @keywords.each do |keyword| %>
  <tr>
    <td><%= keyword.skillId %></td>
    <td><%= keyword.keyword %></td>
    <td><%= link_to 'Show', keyword %></td>
    <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
    <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Skillid:</b>
  <%= @keyword.skillId %>
</p>

<p>
  <b>Keyword:</b>
  <%= @keyword.keyword %>
</p>


<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>